// <auto-generated />
namespace MVC_2._5Garage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init16));
        
        string IMigrationMetadata.Id
        {
            get { return "201712201004159_init16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
