// <auto-generated />
namespace MVC_2._5Garage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211133002_init2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
