// <auto-generated />
namespace MVC_2._5Garage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init13));
        
        string IMigrationMetadata.Id
        {
            get { return "201712200941059_init13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
